config/routes.rb
Rails.application.routes.draw do
  root to: "homes#top"
  get "/about" => "homes#about"

  # devise_for :users, controllers: {
  #   registrations: 'users/registrations'
  # }
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  get "/my_page" => "users#show"
  get "/information/edit" => "users#edit"
  patch "/information" => "users#update"
  get "/unsubscribe" => "users#unsubscribe"
  delete "/information" => "users#destroy", as: "destroy_user"

  resources :my_dogs, only: [:new, :create, :edit, :update]
  resources :diaries, only: [:new, :create, :index, :show, :edit, :update]
  resources :strolls, only: [:new, :create, :index, :show, :edit, :update, :destroy]
  resources :photos, only: [:create, :index, :show, :edit, :update, :destroy]
  delete "/pins/destroy_all" => "pins#destroy"
  resources :pins, only: [:new, :create]

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable

  has_many :my_dogs, dependent: :destroy
  has_many :photos, dependent: :destroy
  has_many :diaries, dependent: :destroy
  has_many :strolls, dependent: :destroy
  has_many :pins, dependent: :destroy

  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :user_name, presence: true, uniqueness: true, length: { minimum: 2, maximum: 20 }
  validates :email, presence: true, uniqueness: true

  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.last_name = "ゲスト"
      user.first_name = "太郎"
      user.user_name = "ゲスト"
    end
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]


  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
  def guest_sign_in
    user = User.guest
    sign_in user
    flash[:alert] = 'ゲストユーザーとしてログインしました。'
    redirect_to my_page_path
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = current_user
    @my_dogs = current_user.my_dogs.page(params[:page]).per(5)
    @date = Date.current
    # @bigは大型犬
    @big = MyDog.sizes.key(0)
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.email == 'guest@example.com'
      flash[:alert] = 'ゲストユーザーは編集できません。'
      redirect_to my_page_path
    else
      @user.update(user_params)
      flash[:notice] = 'ユーザー情報を編集しました。'
      redirect_to my_page_path(current_user.id)
    end
  end

  def unsubscribe
    @user = current_user
  end

  def destroy
    @user = current_user
    if @user.email == 'guest@example.com'
      flash[:alert] = 'ゲストユーザーは削除できません。'
      redirect_to my_page_path
    else
      @user.destroy
      flash[:notice] = '退会しました。またのご利用をお待ちしています！'
      redirect_to root_path
    end
  end


  private
    def user_params
      params.require(:user).permit(:email, :last_name, :first_name, :user_name)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="container_fuluid other-images jumbotron m-0" style="width: 100%; min-height: 600px;">
  <!--画面幅 768px 以上は以下を表示-->
  <div class="d-none d-md-block">
    <div class="row justify-content-center">
      <div class="col-xl-7 col-lg-10 col-md-11 beige-box p-4">
        <div class="row">
          <div class="col-md-4 m-4">
            <h3 class="text-center border-bottom border-green-10">会員情報編集</h3>
          </div>
        </div>
        <div class="row m-4 justify-content-center">
          <div class="col-md-12">
            <%= form_with model: @user, url: information_path do |f| %>
              <table class="table">
                <tr>
                  <th class="px-0 text-left">氏名</th>
                  <td class="px-0 text-right"><%= f.label "姓" %> <%= f.text_field :last_name, autofocus: true, autocomplete: "last_name" %></td>
                  <td class="px-0 text-right"><%= f.label "名" %> <%= f.text_field :first_name, autofocus: true, autocomplete: "first_name" %></td>
                </tr>
                <tr>
                  <th class="px-0 text-left">ユーザーネーム</th>
                  <td class="px-0 text-right"><%= f.text_field :user_name, autofocus: true, autocomplete: "user_name" %></td>
                </tr>
                <tr>
                  <th class="px-0 text-left">メールアドレス</th>
                  <td class="px-0 text-right"><%= f.email_field :email, autofocus: true, autocomplete: "email" %></td>
                </tr>
                <tr class="pt-5">
                  <th class="pt-5 px-0 text-left"></th>
                  <td class="pt-5 px-0 text-left"><%= f.submit "変更する", class: "btn btn-pink2 font-weight-bold text-green" %></td>
                  <td class="pt-5 px-0 text-left"><%= link_to "退会する", unsubscribe_path, class: "btn btn-green font-weight-bold text-lightpink" %></td>
                </tr>
              </table>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>

  <!--画面幅 768px 未満は以下を表示-->
  <div class="d-block d-md-none">
    <div class="row justify-content-center">
      <div class="beige-box m-0auto py-5 px-4" style="width: 80%;">
        <div class="row justify-content-center">
          <div class="col-sm-6 col-10 m-4">
            <h3 class="text-center border-bottom border-green-10">会員情報編集</h3>
          </div>
        </div>
        <div class="row justify-content-center">
          <%= form_with model: @user, url: information_path do |f| %>
            <div class="col-12">
              <div class="text-left">氏名</div>
              <div class="pl-4 text-right"><%= f.label "姓" %> <%= f.text_field :last_name, autofocus: true, autocomplete: "last_name" %></div>
              <div class="pl-4 text-right"><%= f.label "名" %> <%= f.text_field :first_name, autofocus: true, autocomplete: "first_name" %></div>
              <div class="text-left">ユーザーネーム</div>
              <div class="text-right"><%= f.text_field :user_name, autofocus: true, autocomplete: "user_name" %></div>
              <div class="text-left">メールアドレス</div>
              <div class="text-right"><%= f.email_field :email, autofocus: true, autocomplete: "email" %></div>
              <div class="my-4 text-right"><%= f.submit "変更する", class: "btn btn-pink2 font-weight-bold text-green" %></div>
              <div class="mb-4 text-right"><%= link_to "退会する", unsubscribe_path, class: "btn btn-green font-weight-bold text-lightpink" %></div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container_fuluid mypage-image" style="width: 100%; min-height: 600px;">
  <div class="box-8">
    <div class="row ml-2 justify-content-start">
      <div class="col-lg-3 col-md-4 col-7">
        <h2 class="box-8 text-center border-bottom border-green-10">マイページ</h2>
      </div>
    </div>
    <div class="row mx-3 justify-content-center">
      <div class="col-lg-7 col-md-11 box-8 pt-0 pb-4 px-4 border border-green">
        <span class="pl-5 font-weight-bold text-pink"><%= flash[:alert] %></span>
        <span class="pl-5 font-weight-bold text-pink"><%= flash[:notice] %></span>
        <div class="row justify-content-center">
          <div class="col-md-10 col-12 px-0">
            <table class="table table-borderless my-3">
              <tr>
                <th class="py-1 px-0">氏名</th>
                <td class="py-1 px-0"><%= @user.last_name %><%= @user.first_name %></td>
              </tr>
              <tr>
                <th class="py-1 px-0">ユーザーネーム</th>
                <td class="py-1 px-0"><%= @user.user_name %></td>
              </tr>
              <tr>
                <th class="py-1 px-0">メールアドレス</th>
                <td class="py-1 px-0"><%= @user.email %></td>
              </tr>
            </table>
          </div>
          <div class="col-md-2 col-8 px-0">
            <%= link_to "会員情報を変更する", information_edit_path(@user.id), class: "btn btn-pink mb-2 p-1 border border-green font-weight-bold text-dark" %>
            <%= link_to "愛犬情報を追加する", new_my_dog_path, class: "btn btn-pink mb-2 p-1 border border-green font-weight-bold text-dark" %>
          </div>
        </div>
      </div>
    </div>

  <!--各愛犬情報-->
  <!--画面幅 576px 以上は以下の表示-->
  <div class="d-none d-md-block">
    <span class="pl-5 font-weight-bold text-pink"><%= flash[:notice_dog] %></span>
    <div class="wrap my-5">
      <ul id="tab-menu" class="mb-0">
        <% @my_dogs.each_with_index do |my_dog, index| %>
          <% if index == 0 %>
            <li class="font-weight-bold"><a href="#tab<%= index %>" class="active"><%= my_dog.name %>ちゃん</a></li>
          <% else %>
            <li class="font-weight-bold"><a href="#tab<%= index %>"><%= my_dog.name %>ちゃん</a></li>
          <% end %>
        <% end %>
      </ul>
      <div id="tab-contents">
        <% @my_dogs.each_with_index do |my_dog, index| %>
          <div id="tab<%= index %>" class="tab">
            <div class="row my-4 mx-3 justify-content-center">
              <div class="col-md-4 col-6">
                <div class="row mb-3 justify-content-center">
                  <%= image_tag my_dog.get_dog_image(250,250) %>
                </div>
              </div>
              <div class="col-md-7 col-11 p-4">
                <div class="row justify-content-end">
                  <div class="col-lg-10 col-md-9 col-12 px-0">
                    <table class="table table-borderless mt-0 mb-4 py-5">
                      <% if my_dog.birthdate.present? %>
                        <tr>
                          <th class="pl-4 pr-2" style="width: 33%;">誕生日</th>
                          <!--format_time()はhelpers/application_helper.rb参照-->
                          <td class="px-0"><%= format_date(my_dog.birthdate) %></td>
                        </tr>
                        <tr>
                          <th class="pl-4 pr-2" style="width: 33%;">サイズ</th>
                          <td class="px-0"><%= my_dog.size_i18n %></td>
                        </tr>
                        <tr>
                          <th class="pl-4 pr-2" style="width: 33%;">年齢</th>
                          <td class="px-0">
                            <% if my_dog.months_old < 1 %>
                              生後1ヶ月未満
                            <% elsif my_dog.years_old < 1 %>
                              生後<%= my_dog.months_old.to_i %>ヶ月
                            <% else %>
                              <%= my_dog.years_old %>歳
                            <% end %>
                          </td>
                        </tr>
                        <tr>
                          <th class="pl-4 pr-2" style="width: 33%;">人間年齢</th>
                          <td class="px-0">
                            <!--大型犬で1歳未満-->
                            <% if my_dog.size == @big && my_dog.years_old < 1 %>
                              12歳未満
                            <!--大型犬で1歳以上-->
                            <% elsif my_dog.size == @big && my_dog.years_old >= 1 %>
                              <%= (my_dog.years_old - 1)*7 +12 %>歳から<%= (my_dog.years_old - 1)*7 +19 %>歳ぐらい
                            <!--小型・中型犬で生後1ヶ月以下-->
                            <% elsif my_dog.size != @big && my_dog.months_old <= 1 %>
                              1歳未満
                            <!--小型・中型犬で生後3ヶ月以下-->
                            <% elsif my_dog.size != @big && my_dog.months_old <= 3 %>
                              1歳から5歳ぐらい
                            <!--小型・中型犬で生後6ヶ月以下-->
                            <% elsif my_dog.size != @big && my_dog.months_old <= 6 %>
                              5歳から9歳ぐらい
                            <!--小型・中型犬で生後9ヶ月以下-->
                            <% elsif my_dog.size != @big && my_dog.months_old <= 9 %>
                              9歳から13歳ぐらい
                            <!--小型・中型犬で1歳以下-->
                            <% elsif my_dog.size != @big &&my_dog. years_old <= 1 %>
                              13歳から17歳ぐらい
                            <!--小型・中型犬で1歳6ヶ月以下-->
                            <% elsif my_dog.size != @big && my_dog.months_old <= 18 %>
                              17歳から20歳ぐらい
                            <!--小型・中型犬で2歳以下-->
                            <% elsif my_dog.size != @big && my_dog.years_old <= 2 %>
                              20歳から24歳ぐらい
                            <!--小型・中型犬で3歳以上-->
                            <% else %>
                              <%= (my_dog.years_old - 2)*4 +24 %>歳から<%= (my_dog.years_old - 2)*4 +28 %>歳ぐらい
                            <% end %>
                          </td>
                        </tr>
                      <% else %>
                        <tr>
                          <th class="pl-4 pr-2" style="width: 33%;">サイズ</th>
                          <td class="px-0"><%= my_dog.size_i18n %></td>
                        </tr>
                        <tr>
                          <th class="pl-4 pr-2" style="width: 33%;">誕生日</th>
                          <td class="px-0">未登録</td>
                        </tr>
                      <% end %>
                    </table>
                  </div>
                  <div class="col-lg-2 col-md-3 col-8 px-0">
                    <!--個々の愛犬のカレンダーへのリンク-->
                    <%= link_to "カレンダー", diaries_path(path_id: 1, my_dog_id: my_dog.id), class: "btn btn-pink mb-2 p-1 border border-green font-weight-bold text-dark" %>
                    <%= link_to "愛犬情報を変更する", edit_my_dog_path(my_dog.id), class: "btn btn-pink mb-2 p-1 border border-green font-weight-bold text-dark" %>
                  </div>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <!--画面幅 576px 未満は以下の表示-->
  <div class="d-block d-md-none">
    <span class="pl-5 font-weight-bold text-pink"><%= flash[:notice_dog] %></span>
      <% @my_dogs.each do |my_dog| %>
        <div class="row my-4 mx-3 justify-content-center">
          <div class="col-md-4 col-6">
            <div class="row mb-3 justify-content-center">
              <%= image_tag my_dog.get_dog_image(250,250), class: "border border-green" %>
            </div>
          </div>
          <div class="col-md-7 col-11 box-8 p-4 border border-green">
            <div class="row justify-content-end">
              <div class="col-lg-10 col-md-9 col-12 px-0">
                <table class="table table-borderless mt-0 mb-4 py-5">
                  <tr>
                    <th colspan="2" class="h4 px-0 font-weight-bold text-left"><%= my_dog.name %>ちゃん</th>
                  </tr>
                  <% if my_dog.birthdate.present? %>
                    <tr>
                      <th class="pl-4 pr-2" style="width: 33%;">誕生日</th>
                      <!--format_time()はhelpers/application_helper.rb参照-->
                      <td class="px-0"><%= format_date(my_dog.birthdate) %></td>
                    </tr>
                    <tr>
                      <th class="pl-4 pr-2" style="width: 33%;">サイズ</th>
                      <td class="px-0"><%= my_dog.size_i18n %></td>
                    </tr>
                    <tr>
                      <th class="pl-4 pr-2" style="width: 33%;">年齢</th>
                      <td class="px-0">
                        <% if my_dog.months_old < 1 %>
                          生後1ヶ月未満
                        <% elsif my_dog.years_old < 1 %>
                          生後<%= my_dog.months_old.to_i %>ヶ月
                        <% else %>
                          <%= my_dog.years_old %>歳
                        <% end %>
                      </td>
                    </tr>
                    <tr>
                      <th class="pl-4 pr-2" style="width: 33%;">人間年齢</th>
                      <td class="px-0">
                        <!--大型犬で1歳未満-->
                        <% if my_dog.size == @big && my_dog.years_old < 1 %>
                          12歳未満
                        <!--大型犬で1歳以上-->
                        <% elsif my_dog.size == @big && my_dog.years_old >= 1 %>
                          <%= (my_dog.years_old - 1)*7 +12 %>歳から<%= (my_dog.years_old - 1)*7 +19 %>歳ぐらい
                        <!--小型・中型犬で生後1ヶ月以下-->
                        <% elsif my_dog.size != @big && my_dog.months_old <= 1 %>
                          1歳未満
                        <!--小型・中型犬で生後3ヶ月以下-->
                        <% elsif my_dog.size != @big && my_dog.months_old <= 3 %>
                          1歳から5歳ぐらい
                        <!--小型・中型犬で生後6ヶ月以下-->
                        <% elsif my_dog.size != @big && my_dog.months_old <= 6 %>
                          5歳から9歳ぐらい
                        <!--小型・中型犬で生後9ヶ月以下-->
                        <% elsif my_dog.size != @big && my_dog.months_old <= 9 %>
                          9歳から13歳ぐらい
                        <!--小型・中型犬で1歳以下-->
                        <% elsif my_dog.size != @big &&my_dog. years_old <= 1 %>
                          13歳から17歳ぐらい
                        <!--小型・中型犬で1歳6ヶ月以下-->
                        <% elsif my_dog.size != @big && my_dog.months_old <= 18 %>
                          17歳から20歳ぐらい
                        <!--小型・中型犬で2歳以下-->
                        <% elsif my_dog.size != @big && my_dog.years_old <= 2 %>
                          20歳から24歳ぐらい
                        <!--小型・中型犬で3歳以上-->
                        <% else %>
                          <%= (my_dog.years_old - 2)*4 +24 %>歳から<%= (my_dog.years_old - 2)*4 +28 %>歳ぐらい
                        <% end %>
                      </td>
                    </tr>
                  <% else %>
                    <tr>
                      <th class="pl-4 pr-2" style="width: 33%;">サイズ</th>
                      <td class="px-0"><%= my_dog.size_i18n %></td>
                    </tr>
                    <tr>
                      <th class="pl-4 pr-2" style="width: 33%;">誕生日</th>
                      <td class="px-0">未登録</td>
                    </tr>
                  <% end %>
                </table>
              </div>
              <div class="col-lg-2 col-md-3 col-8 px-0">
                <!--個々の愛犬のカレンダーへのリンク-->
                <%= link_to "カレンダー", diaries_path(path_id: 1, my_dog_id: my_dog.id), class: "btn btn-pink mb-2 p-1 border border-green font-weight-bold text-success" %>
                <%= link_to "愛犬情報を変更する", edit_my_dog_path(my_dog.id), class: "btn btn-pink mb-2 p-1 border border-green font-weight-bold text-success" %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
    <% if MyDog.where(user_id: @user.id).count >= 3 %>
      <div class="pr-3 text-center font-weight-bold">他の愛犬の表示はこちらから</div>
      <%= paginate @my_dogs %>
    <% end %>
    <div class="row mt-5 mx-3 justify-content-end">
      <div class="col-lg-6 col-md-11 col-12 box-8">
        <span class="small text-right">愛犬年齢が1歳未満の場合、<br>
          月齢の計算は365日を12で割って1ヶ月(30.416日)としていますので誤差があります。<br>
          ご了承ください。<br>
          人間年齢は、「犬の年齢を人年齢に換算する計算式（引用：京都中央動物病院HP）」を参考にしています。
        </span>
      </div>
    </div>
  </div>
</div>

app/views/users/unsubscribe.html.erb
<div class="container_fuluid other-images" style="width: 100%; min-height: 600px;">
  <!--画面幅 576px 以上は以下の表示-->
  <div class="d-none d-sm-block">
    <div class="row justify-content-center" style="height: 500px;">
      <div class="col-xl-6 col-lg-7 col-md-9 col-sm-10 beige-box my-5">
        <div class="row mt-5 mb-3 justify-content-center">
          <div class="col-xl-7 col-lg-8 col-md-9 col-sm-8 m-4">
            <h3 class="text-center border-bottom border-green-10"><strong>本当に退会しますか？</strong></h3>
          </div>
        </div>
        <div class="row mb-5 justify-content-center">
          <div class="col-md-9 col-sm-11 m-4 text-center">
            <span>
              退会すると会員登録情報や<br>
              これまでの日記が閲覧できなくなります。<br>
              <br>
              退会する場合は、<br>
              「退会する」をクリックしてください。
            </span>
          </div>
        </div>
        <div class="row my-4 justify-content-between">
          <div class="col-md-5 col-sm-4 m-4 text-center">
            <%= link_to "退会しない", my_page_path, class: "btn btn-pink2 font-weight-bold text-green" %>
          </div>
          <div class="col-md-5 col-sm-4 m-4 text-center">
            <%= link_to "退会する", destroy_user_path, method: :delete, "data-confirm" => "本当に退会しますか？", class: "btn btn-green font-weight-bold text-lightpink" %>
          </div>
        </div>
      </div>
    </div>
  </div>

  <!--画面幅 576px 未満は以下の表示-->
  <div class="d-block d-sm-none">
    <div class="row justify-content-center">
      <div class="beige-box my-5 mx-0auto py-5 px-4" style="width: 80%;">
        <div class="row justify-content-center">
          <div class="col-12">
            <h4 class="text-center border-bottom border-green-10">本当に退会しますか？</h4>
            <div class="row mb-4 justify-content-center">
              <div class="col-11 m-4 text-center">
                <span>
                  退会すると会員登録情報や<br>
                  これまでの日記が<br>
                  閲覧できなくなります。<br>
                  <br>
                  退会する場合は、<br>
                  「退会する」をクリックしてください。
                </span>
              </div>
            </div>
            <div class="row justify-content-between">
              <div class="col-6 text-center">
                <%= link_to "退会しない", my_page_path, class: "btn btn-pink2 font-weight-bold text-green" %>
              </div>
              <div class="col-5 text-center">
                <%= link_to "退会する", destroy_user_path, method: :delete, "data-confirm" => "本当に退会しますか？", class: "btn btn-green font-weight-bold text-lightpink" %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>