config/routes.rb
Rails.application.routes.draw do
  root to: "homes#top"
  get "/about" => "homes#about"

  # devise_for :users, controllers: {
  #   registrations: 'users/registrations'
  # }
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  get "/my_page" => "users#show"
  get "/information/edit" => "users#edit"
  patch "/information" => "users#update"
  get "/unsubscribe" => "users#unsubscribe"
  delete "/information" => "users#destroy", as: "destroy_user"

  resources :my_dogs, only: [:new, :create, :edit, :update]
  resources :diaries, only: [:new, :create, :index, :show, :edit, :update]
  resources :strolls, only: [:new, :create, :index, :show, :edit, :update, :destroy]
  resources :photos, only: [:create, :index, :show, :edit, :update, :destroy]
  delete "/pins/destroy_all" => "pins#destroy"
  resources :pins, only: [:new, :create]

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
    @path_id = params[:path_id].to_i
    @foods = ["普通", "多い", "少ない"]
    @dookies = ["少ない", "普通", "多い"]
    @times = [75, 50, 60, 70, 55, 0]
    @distances = [2050, 1490, 1960, 2160, 1870, 1640]
  end

  def guest_sign_in
    user = User.find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.last_name = "ゲスト"
      user.first_name = "太郎"
      user.user_name = "ゲスト"
    end
    sign_in user
    redirect_to root_path, notice: 'ゲストユーザーとしてログインしました。'
  end
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/homes/top.html.erb
<div class="container_fuluid top-bg-image jumbotron m-0" style="width: 100%; min-height: 600px;">
  <div class="row justify-content-center" style="min-height: 350px;">
    <div class="col-xl-6 col-lg-8 col-md-10 col-sm-12 col-12 top-box text-center">
      <span class="pl-5 font-weight-bold text-pink"><%= flash[:notice] %></span>
      <div class="row mt-3 mx-0 justify-content-center">
        <div class="col-12 mx-0 px-0">
          <h2 class="font-weight-bold">ようこそ、<br>Loveドッグダイアリーへ！</h2>
        </div>
      </div>
      <div class="row mt-2 mx-0 justify-content-center">
        <div class="col-12 m-0auto">
          <span class="mt-4 mx-0auto">
            Loveドッグダイアリーでは、<br>
            わんちゃんとのお散歩ルートや<br>
            距離、散歩時間、速度、<br>
            その時に撮った写真、その日の健康状態などを<br>
            日記として記録できます<br>
          </span>
        </div>
      </div>
      <div class="row mt-4 mx-0 justify-content-center">
        <% if user_signed_in? %>
          <!--サインイン中は新規登録、ログインは非表示-->
          <div class="col-md-3 ml-5 top-balloon2">
            <div class="row">
              <div class="col-12">
                <strong><%= link_to "散歩ルート見本", about_path(path_id: 0), class: 'text-pink' %></strong><br>
              </div>
            </div>
            <div class="row mt-2">
              <div class="col-12">
                <strong><%= link_to "カレンダー見本", about_path(path_id: 1), class: 'text-pink' %></strong>
              </div>
            </div>
            <div class="row mt-2">
              <div class="col-12">
                <strong><%= link_to "日記見本", about_path(path_id: 2), class: 'text-pink' %></strong>
              </div>
            </div>
          </div>
        <% else %>
          <div class="col-md-3 col-4 ml-0 px-0 top-balloon">
            <div class="row">
              <div class="col-12">
                <strong><%= link_to "新規登録", new_user_registration_path, class: 'text-pink' %></strong><br>
              </div>
            </div>
            <div class="row mt-2">
              <div class="col-12">
                <strong><%= link_to "ログイン", new_user_session_path, class: 'text-pink' %></strong>
              </div>
            </div>
            <div class="row mt-2">
              <div class="col-12">
                <strong><%= link_to 'ゲストログイン', users_guest_sign_in_path, method: :post, class: "text-dark" %></strong>
              </div>
            </div>
          </div>
          <div class="col-md-3 col-4 px-0 top-balloon2">
            <div class="row">
              <div class="col-12">
                <strong><%= link_to "散歩ルート見本", about_path(path_id: 0), class: 'text-pink' %></strong><br>
              </div>
            </div>
            <div class="row mt-2">
              <div class="col-12">
                <strong><%= link_to "カレンダー見本", about_path(path_id: 1), class: 'text-pink' %></strong>
              </div>
            </div>
            <div class="row mt-2">
              <div class="col-12">
                <strong><%= link_to "日記見本", about_path(path_id: 2), class: 'text-pink' %></strong>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <div class="row" style="min-height: 140px;">
  </div>
</div>