config/routes.rb
Rails.application.routes.draw do
  root to: "homes#top"
  get "/about" => "homes#about"

  # devise_for :users, controllers: {
  #   registrations: 'users/registrations'
  # }
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  get "/my_page" => "users#show"
  get "/information/edit" => "users#edit"
  patch "/information" => "users#update"
  get "/unsubscribe" => "users#unsubscribe"
  delete "/information" => "users#destroy", as: "destroy_user"

  resources :my_dogs, only: [:new, :create, :edit, :update]
  resources :diaries, only: [:new, :create, :index, :show, :edit, :update]
  resources :strolls, only: [:new, :create, :index, :show, :edit, :update, :destroy]
  resources :photos, only: [:create, :index, :show, :edit, :update, :destroy]
  delete "/pins/destroy_all" => "pins#destroy"
  resources :pins, only: [:new, :create]

end

app/models/stroll.rb
class Stroll < ApplicationRecord
  enum vitality_condition: {
    slowly: 0, # のんびり
    a_little_slowly: 1, # ややのんびり
    usually: 2, # 普通
    a_little_vitality: 3, # ちょっと元気
    quite_vitality: 4, # すごく元気
  }

  belongs_to :user
  belongs_to :diary
  belongs_to :my_dog
  has_many :pins, dependent: :destroy

  validates :user_id, presence: true
  validates :diary_id, presence: true
  validates :my_dog_id, presence: true
  validates :start_time, presence: true
  validates :end_time, presence: true
  validates :vitality_condition, presence: true

  def time_of_stroll
    (end_time - start_time).floor / 60
  end

end

app/controllers/strolls_controller.rb
class StrollsController < ApplicationController
  before_action :check_dog, only:[:new, :index, :show, :edit]
  before_action :ensure_user, only:[:show, :edit, :update]

  def new
    @stroll = Stroll.new
    @vitality_conditions = Stroll.vitality_conditions
    @diary_id = params[:diary_id]
    @dog_id = params[:dog_id]
  end

  def create
    @stroll = Stroll.new(stroll_params)
    @stroll.user_id = current_user.id
    if @stroll.save
      flash[:notice_stroll] = '散歩情報を登録しました。'
      redirect_to diary_path(@stroll.diary.id)
    else
      flash[:notice_stroll] = '時間と「元気の良さ」を設定してください。'
      redirect_to diary_path(@stroll.diary.id)
    end
  end

  def index
      @strolls = current_user.strolls.page(params[:page]).per(10)
  end

  def show
    @pins = @stroll.pins.all
    @pin = @stroll.pins.order(updated_at: :desc).first
  end

  def edit
    @vitality_conditions = Stroll.vitality_conditions
  end

  def update
    @stroll = Stroll.find(params[:id])
    @stroll.user_id = current_user.id
    @stroll.update(stroll_params)
    flash[:notice_stroll] = '散歩情報を編集しました。'
    redirect_to diary_path(@stroll.diary.id)
  end

  private

  def stroll_params
    params.require(:stroll).permit(:user_id, :diary_id, :my_dog_id, :start_time, :end_time, :vitality_condition, :memo)
  end

  def ensure_user
    @stroll = Stroll.find(params[:id])
    unless @stroll.user_id == current_user.id
      redirect_to strolls_path
    end
  end

  def check_dog
    if current_user.my_dogs.empty?
      flash[:info] = "先に愛犬情報を登録してください"
      redirect_to new_my_dog_path
    end
  end
end

app/helpers/strolls_helper.rb
module StrollsHelper
end

app/views/strolls/edit.html.erb
<div class="container_fuluid other-images jumbotron m-0">
  <!--画面幅 768px 以上は以下の表示-->
  <div class="d-none d-md-block">
    <div class="row mx-0auto justify-content-center">
      <div class="col-lg-8 col-md-9  col-12 beige-box my-5">
        <div class="row justify-content-center">
          <div class="col-xl-4 col-lg-5 col-md-6 col-11 mt-5">
            <h3 class="text-center border-bottom border-green-10">散歩概要の編集</h3>
          </div>
        </div>
        <div class="row m-4 justify-content-center">
          <%= form_with model: @stroll do |f| %>
            <table class="table">
              <tr>
                <th class="pl-4">開始時間</th>
                <td><%= f.time_field :start_time %></td>
              </tr>
              <tr>
                <th class="pl-4">終了時間</th>
                <td><%= f.time_field :end_time %></td>
              </tr>
              <tr>
                <th class="pl-4">散歩メモ</th>
                <td>
                  <div><%= f.text_area :memo, style: "width: 90%; min-height: 70px;" %></div>
                </td>
              </tr>
              <tr>
                <th class="pl-4">散歩中の元気の良さ</th>
                <td>
                  <%= f.radio_button :vitality_condition, @vitality_conditions.key(0) %>
                  <%= f.label :vitality_condition, Stroll.vitality_conditions_i18n[:slowly], value: :slowly %><br />
                  <%= f.radio_button :vitality_condition, @vitality_conditions.key(1) %>
                  <%= f.label :vitality_condition, Stroll.vitality_conditions_i18n[:a_little_slowly], value: :a_little_slowly %><br />
                  <%= f.radio_button :vitality_condition, @vitality_conditions.key(2) %>
                  <%= f.label :vitality_condition, Stroll.vitality_conditions_i18n[:usually], value: :usually %><br />
                  <%= f.radio_button :vitality_condition, @vitality_conditions.key(3) %>
                  <%= f.label :vitality_condition, Stroll.vitality_conditions_i18n[:a_little_vitality], value: :a_little_vitality %><br />
                  <%= f.radio_button :vitality_condition, @vitality_conditions.key(4) %>
                  <%= f.label :vitality_condition, Stroll.vitality_conditions_i18n[:quite_vitality], value: :quite_vitality %><br />
                </td>
              </tr>
              <tr>
                <th class="px-0 text-right"></th>
                <td class="px-0 text-right"><%= f.submit "変更する", class: "btn btn-green font-weight-bold text-lightpink" %></td>
              </tr>
            </table>
          <% end %>
        </div>
      </div>
    </div>
  </div>

  <!--画面幅 768px 未満は以下の表示-->
  <div class="d-block d-md-none">
    <div class="row justify-content-center">
      <div class="beige-box m-0auto py-5 px-4" style="width: 80%;">
        <div class="row justify-content-center">
          <div class="col-sm-8 col-11 m-4">
            <h3 class="text-center border-bottom border-green-10">散歩概要の編集</h3>
          </div>
        </div>
        <div class="row justify-content-center">
          <%= form_with model: @stroll do |f| %>
            <div class="mb-1 text-left font-weight-bold">開始時間</div>
            <div class="pl-5"><%= f.time_field :start_time %></div>
            <div class="mt-4 mb-1 text-left font-weight-bold">終了時間</div>
            <div class="pl-5"><%= f.time_field :end_time %></div>
            <div class="mt-4 mb-1 text-left font-weight-bold">散歩メモ</div>
            <div class="pl-5"><%= f.text_area :memo, style: "width: 90%; min-height: 70px;" %></div>
            <div class="mt-4 mb-1 text-left font-weight-bold">散歩中の元気の良さ</div>
            <div class="mb-4 pl-5">
              <%= f.radio_button :vitality_condition, @vitality_conditions.key(0) %>
              <%= f.label :vitality_condition, Stroll.vitality_conditions_i18n[:slowly], value: :slowly %><br />
              <%= f.radio_button :vitality_condition, @vitality_conditions.key(1) %>
              <%= f.label :vitality_condition, Stroll.vitality_conditions_i18n[:a_little_slowly], value: :a_little_slowly %><br />
              <%= f.radio_button :vitality_condition, @vitality_conditions.key(2) %>
              <%= f.label :vitality_condition, Stroll.vitality_conditions_i18n[:usually], value: :usually %><br />
              <%= f.radio_button :vitality_condition, @vitality_conditions.key(3) %>
              <%= f.label :vitality_condition, Stroll.vitality_conditions_i18n[:a_little_vitality], value: :a_little_vitality %><br />
              <%= f.radio_button :vitality_condition, @vitality_conditions.key(4) %>
              <%= f.label :vitality_condition, Stroll.vitality_conditions_i18n[:quite_vitality], value: :quite_vitality %><br />
            </div>
            <div class="pl-4 text-right"><%= f.submit "変更する", class: "btn btn-green font-weight-bold text-lightpink" %></div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/strolls/index.html.erb
<div class="container_fuluid other-images jumbotron m-0" style="width: 100%; min-height: 600px;">
  <div class="row justify-content-center">
    <div class="col-xl-6 col-lg-8 col-md-8 col-sm-9 col-11 beige-box my-5">
      <div class="row">
        <div class="col-md-6 col-10 m-2">
          <h3 class="text-center border-bottom border-green-10 mb-0">お散歩ルート一覧</h3>
        </div>
      </div>
      <div class="row mx-0 justify-content-center">
        <div class="col-lg-8 col-sm-10 col-12">
          <% if @strolls.present? %>
            <!--お散歩ルートが1件以上の場合-->
            <span>
              ルート名をクリックすると、地図が確認できます<br>
              お散歩ルートの追加は日記から可能です
            </span>
          <% else %>
            <!--お散歩ルートが0件の場合-->
            <span>日記からお散歩ルートを登録すると一覧に表示されます</span>
          <% end %>
        </div>
      </div>
      <!--画面幅 576px 以上は以下の表示-->
      <div class="d-none d-sm-block">
        <div class="row m-4 justify-content-center">
          <div class="col-7">
            <table class="table">
              <tr>
                <th class="px-0 text-left">お散歩ルート</th>
                <th class="px-0 text-right">お散歩距離</th>
              </tr>
              <% @strolls.each do |stroll| %>
                <% stroll.pins.pluck(:title).uniq.each do |title| %>
                  <tr>
                    <th class="px-0 text-left">
                      <%= link_to stroll_path(stroll.id), data: {"turbolinks"=>false} do %>
                        <div class="scroll" style="width: 150px; max-height: 40px;"><%= title %></div>
                      <% end %>
                    </th>
                    <td class="px-0 text-right">
                      <!--散歩距離の計算-->
                      <%= stroll.pins.sum(:distance).to_i %> m
                    </td>
                  </tr>
                <% end %>
              <% end %>
            </table>
          </div>
        </div>
      </div>

      <!--画面幅 576px 未満は以下の表示-->
      <div class="d-block d-sm-none">
        <div class="row mt-3 justify-content-center">
          <div class="col-11">
            <table class="table">
              <tr>
                <th class="pl-3">お散歩ルート</th>
                <th class="pr-4 text-right">お散歩距離</th>
              </tr>
              <% @strolls.each do |stroll| %>
                <% stroll.pins.pluck(:title).uniq.each do |title| %>
                  <tr>
                    <th class="px-3 text-left">
                      <%= link_to stroll_path(stroll.id), data: {"turbolinks"=>false} do %>
                        <div class="scroll pr-0 pl-2" style="width: 100%; max-height: 40px;"><%= title %></div>
                      <% end %>
                    </th>
                    <td class="pr-5 text-right">
                      <!--散歩距離の計算-->
                      <%= stroll.pins.sum(:distance).to_i %> m
                    </td>
                  </tr>
                <% end %>
              <% end %>
            </table>
          </div>
          <%= paginate @strolls %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/strolls/new.html.erb
<div class="container_fuluid other-images jumbotron m-0">
  <!--画面幅 768px 以上は以下の表示-->
  <div class="d-none d-md-block">
    <div class="row mx-0auto justify-content-center">
      <div class="col-lg-8 col-md-9  col-12 beige-box my-5">
        <div class="row justify-content-center">
          <div class="col-xl-4 col-lg-5 col-md-6 col-11 mt-5">
            <h3 class="text-center border-bottom border-green-10">散歩概要の登録</h3>
          </div>
        </div>
        <div class="row m-4 justify-content-center">
          <%= form_with model: @stroll do |f| %>
            <table class="table">
              <tr>
                <th class="pl-4">開始時間</th>
                <td><%= f.time_field :start_time %></td>
              </tr>
              <tr>
                <th class="pl-4">終了時間</th>
                <td><%= f.time_field :end_time %></td>
              </tr>
              <tr>
                <th class="pl-4">散歩メモ</th>
                <td>
                  <div><%= f.text_area :memo, style: "width: 90%; min-height: 70px;" %></div>
                </td>
              </tr>
              <tr>
                <th class="pl-4">散歩中の元気の良さ</th>
                <td>
                  <%= f.radio_button :vitality_condition, @vitality_conditions.key(0) %>
                  <%= f.label :vitality_condition, Stroll.vitality_conditions_i18n[:slowly], value: :slowly %><br />
                  <%= f.radio_button :vitality_condition, @vitality_conditions.key(1) %>
                  <%= f.label :vitality_condition, Stroll.vitality_conditions_i18n[:a_little_slowly], value: :a_little_slowly %><br />
                  <%= f.radio_button :vitality_condition, @vitality_conditions.key(2) %>
                  <%= f.label :vitality_condition, Stroll.vitality_conditions_i18n[:usually], value: :usually %><br />
                  <%= f.radio_button :vitality_condition, @vitality_conditions.key(3) %>
                  <%= f.label :vitality_condition, Stroll.vitality_conditions_i18n[:a_little_vitality], value: :a_little_vitality %><br />
                  <%= f.radio_button :vitality_condition, @vitality_conditions.key(4) %>
                  <%= f.label :vitality_condition, Stroll.vitality_conditions_i18n[:quite_vitality], value: :quite_vitality %><br />
                </td>
              </tr>
              <%= f.hidden_field :diary_id, :value => @diary_id %>
              <%= f.hidden_field :my_dog_id, :value => @dog_id %>
              <tr>
                <th class="px-0 text-right"></th>
                <td class="px-0 text-right"><%= f.submit "変更する", class: "btn btn-green font-weight-bold text-lightpink" %></td>
              </tr>
            </table>
          <% end %>
        </div>
      </div>
    </div>
  </div>

  <!--画面幅 768px 未満は以下の表示-->
  <div class="d-block d-md-none">
    <div class="row justify-content-center">
      <div class="beige-box m-0auto py-5 px-4" style="width: 80%;">
        <div class="row justify-content-center">
          <div class="col-sm-8 col-11 m-4">
            <h3 class="text-center border-bottom border-green-10">散歩概要の登録</h3>
          </div>
        </div>
        <div class="row justify-content-center">
          <%= form_with model: @stroll do |f| %>
            <div class="mb-1 text-left font-weight-bold">開始時間</div>
            <div class="pl-5"><%= f.time_field :start_time %></div>
            <div class="mt-4 mb-1 text-left font-weight-bold">終了時間</div>
            <div class="pl-5"><%= f.time_field :end_time %></div>
            <div class="mt-4 mb-1 text-left font-weight-bold">散歩メモ</div>
            <div class="pl-5"><%= f.text_area :memo, style: "width: 90%; min-height: 70px;" %></div>
            <div class="mt-4 mb-1 text-left font-weight-bold">散歩中の元気の良さ</div>
            <div class="mb-4 pl-5">
              <label>
              <%= f.radio_button :vitality_condition, @vitality_conditions.key(0) %>

              <%= f.label :vitality_condition, Stroll.vitality_conditions_i18n[:slowly], value: :slowly, style: "cursor: pointer;" %><br />

              <%= f.radio_button :vitality_condition, @vitality_conditions.key(1) %>
              <%= f.label :vitality_condition, Stroll.vitality_conditions_i18n[:a_little_slowly], value: :a_little_slowly %><br />
              <%= f.radio_button :vitality_condition, @vitality_conditions.key(2) %>
              <%= f.label :vitality_condition, Stroll.vitality_conditions_i18n[:usually], value: :usually %><br />
              <%= f.radio_button :vitality_condition, @vitality_conditions.key(3) %>
              <%= f.label :vitality_condition, Stroll.vitality_conditions_i18n[:a_little_vitality], value: :a_little_vitality %><br />
              <%= f.radio_button :vitality_condition, @vitality_conditions.key(4) %>
              <%= f.label :vitality_condition, Stroll.vitality_conditions_i18n[:quite_vitality], value: :quite_vitality %><br />
            </label>
            </div>
            <%= f.hidden_field :diary_id, :value => @diary_id %>
            <%= f.hidden_field :my_dog_id, :value => @dog_id %>
            <div class="pl-4 text-right"><%= f.submit "保存する", class: "btn btn-green font-weight-bold text-lightpink" %></div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/strolls/show.html.erb
<style>
  /* 地図のサイズ */
  #map_show {
    height: 550px;
    width: 100%;
  }
</style>
<script>
  // 初期マップの設定
  let map_show;
  function initMap() {
    // 地図の中心地
    const center = {lat: <%= @pin.latitude %>, lng:<%= @pin.longitude %> };
    const options = {zoom: 15, scaleControl: true, center: center};
    map_show = new google.maps.Map(
      document.getElementById('map_show'), options);
    // マーカーの位置
    let road_pin = []
    let mk = []
    <% @pins.each_with_index do |pin,index| %>
      road_pin[<%= index %>] = {lat: <%= pin.latitude %>, lng: <%= pin.longitude %>};
      mk[<%= index %>] = new google.maps.Marker({position: road_pin[0], map: map_show});
      <% if index != 0 %>
        // ポリラインの描画
        new google.maps.Polyline({path: [road_pin[<%= index %>], road_pin[<%= index - 1 %>]], map: map_show});
      <% end %>
    <% end %>
  }
</script>
<script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLE_MAP_API_KEY'] %>&callback=initMap" async defer></script>

<!--地図とメッセージの要素 -->
<div class="container_fuluid map-image m-0">
  <div id="map_show"></div>
  <div class="box-8 p-5">
    <% pins = @pins.sum(:distance).to_i %>
    <!--画面幅768px以上の場合-->
    <div class="d-none d-md-block row justify-content-center">
      <div class="box-8 mt-3 text-center">
        <span class="mr-5 h4 font-weight-bold border-bottom border-pink-medium">お散歩距離 <%= pins %> m</span>
        <span class="ml-5 mr-2 btn btn-pink font-weight-bold"><%= link_to "散歩ルートを削除する", pins_destroy_all_path(stroll_id: @stroll.id), method: :delete, "data-confirm" => "本当に削除しますか？", class: "text-success" %></span>
      </div>
    </div>
    <!--画面幅768px未満の場合-->
    <div class="d-block d-md-none">
      <div class="row justify-content-center">
        <div class="box-8 mt-3 text-center">
          <span class="h4 font-weight-bold border-bottom border-pink-medium">お散歩距離 <%= pins %> m</span>
        </div>
      </div>
      <div class="row justify-content-center">
        <div class="box-8 mt-3 text-center">
          <span class="btn btn-pink font-weight-bold"><%= link_to "散歩ルートを削除する", pins_destroy_all_path(stroll_id: @stroll.id), method: :delete, "data-confirm" => "本当に削除しますか？", class: "text-success" %></span>
        </div>
      </div>
    </div>
  </div>
</div>