config/routes.rb
Rails.application.routes.draw do
  root to: "homes#top"
  get "/about" => "homes#about"

  # devise_for :users, controllers: {
  #   registrations: 'users/registrations'
  # }
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  get "/my_page" => "users#show"
  get "/information/edit" => "users#edit"
  patch "/information" => "users#update"
  get "/unsubscribe" => "users#unsubscribe"
  delete "/information" => "users#destroy", as: "destroy_user"

  resources :my_dogs, only: [:new, :create, :edit, :update]
  resources :diaries, only: [:new, :create, :index, :show, :edit, :update]
  resources :strolls, only: [:new, :create, :index, :show, :edit, :update, :destroy]
  resources :photos, only: [:create, :index, :show, :edit, :update, :destroy]
  delete "/pins/destroy_all" => "pins#destroy"
  resources :pins, only: [:new, :create]

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LoveDogDiary</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <header style="width: 100%; height: 52px;">
      <nav class="navbar navbar-expand-md navbar-light py-0" style="height: 50px;">
        <a class="navbar-brand p-0" href="/">
          <%= image_tag('logo.png') %>
        </a>
        <button class="navbar-toggler btn-white border-white" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon btn text-success"></span>
        </button>
        <div class="collapse navbar-collapse bg-white" style="height: 50px; z-index: 100;" id="navbarNavDropdown">
          <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
              <li class="nav-item btn btn-lightpink my-3 mx-1 p-0">
                <%= link_to "マイページ", my_page_path, class: 'nav-link py-0 px-1 text-success font-weight-bold' %>
              </li>
              <li class="nav-item btn btn-lightpink my-3 mx-1 p-0">
                <%= link_to "カレンダー", diaries_path(path_id: 0), class: 'nav-link py-0 px-1 text-success font-weight-bold' %>
              </li>
              <li class="nav-item btn btn-lightpink my-3 mx-1 p-0">
                <%= link_to "散歩ルート一覧", strolls_path, class: 'nav-link py-0 px-1 text-success font-weight-bold' %>
              </li>
              <li class="nav-item btn btn-lightpink my-3 mx-1 p-0">
                <%= link_to "写真一覧", photos_path, class: 'nav-link py-0 px-1 text-success font-weight-bold' %>
              </li>
              <li class="nav-item btn btn-lightpink my-3 mx-1 p-0">
                <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'nav-link py-0 px-1 text-success font-weight-bold' %>
              </li>
            <% else %>
              <span class="py-3 font-weight-bold"><%= link_to 'ゲストログイン（閲覧用）', users_guest_sign_in_path, method: :post, class: "text-pink" %></span>
              <li class="nav-item btn btn-lightpink my-3 mx-1 p-0">
                <%= link_to "新規登録", new_user_registration_path, class: 'nav-link py-0 px-1 text-success font-weight-bold' %>
              </li>
              <li class="nav-item btn btn-lightpink my-3 mx-1 p-0">
                <%= link_to "ログイン", new_user_session_path, class: 'nav-link py-0 px-1 text-success font-weight-bold' %>
              </li>
            <% end %>
          </ul>
        </div>
        <div class="hamburger-demo-cover"></div>
      </nav>
    </header>
    <main>
      <%= yield %>
    </main>
    <footer class="footer-pink">

    </footer>
  </body>
</html>